version: '3.8'

services:
  backend:
    image: "${BACKEND_IMAGE}:${BACKEND_TAG}" 
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      - PORT=3000

  frontend:
    image: "${FRONTEND_IMAGE}:${FRONTEND_TAG}" 
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - backend