services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"  
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/db.sqlite3:/app/db.sqlite3
    environment:
      - PORT=3000

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend